function [im_bw, im_mask] = autoSegment(im)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 08-Jul-2017
%----------------------------------------------------

% Normalize input data to range in [0,1].
Xmin = min(im(:));
Xmax = max(im(:));
if isequal(Xmax,Xmin)
    im = 0*im;
else
    im = (im - Xmin) ./ (Xmax - Xmin);
end

% Threshold image - adaptive threshold
im_bw = imbinarize(im, 'adaptive', 'Sensitivity', 0.24, 'ForegroundPolarity', 'dark');

% Clear borders
im_bw = imclearborder(im_bw);

% Open mask with disk
radius = 8;
decomposition = 6;
se = strel('disk', radius, decomposition);
im_bw = imopen(im_bw, se);

% Create masked image.
im_mask = im;
im_mask(~im_bw) = 0;
end

% Think about using homemade imageSegmenter for QuantDRaCALA